events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # React Router FIX (VERY IMPORTANT)
    location / {
      try_files $uri /index.html;
    }

    # Cache static assets
    location /assets/ {
      expires 1y;
      add_header Cache-Control "public, max-age=31536000, immutable";
    }
  }
}